### ISSUE TITLE
Getting Error to Generate Trace File

### ISSUE THREAD

**Issue by jhrbgergibbibfq** [mesarpe/sonetor#1]
Hi,

I'm getting this error while creating trace file:

~/socialccnsim/sonetor$ ./sonetor.sh examples/example.ini /tmp/tracetest
Traceback (most recent call last):
  File "traffic.py", line 32, in <module>
    from scipy.stats import geom
ImportError: No module named scipy.stats

Even I've been installed Scipy with these commands and verified:

sudo apt-get install python-scipy
sudo python2 get-pip.py
pip2 install scipy

But still getting same error

Please help me asap.

Thanks

**Comment by mesarpe** [comment]
Could you please tell me which version of python you are using?

python --version

Cheers,

2018-04-08 8:23 GMT+02:00 jhrbgergibbibfq <notifications@github.com>:

**Comment by jhrbgergibbibfq** [comment]
Hi, I'm using Python 2.7.6

**Comment by jhrbgergibbibfq** [comment]
BTW I'm using Ubuntu version: 14.04.1-Ubuntu

**Comment by jhrbgergibbibfq** [comment]
Most Respected Dr 
Would you please tell me what I have to do to create my trace.

**Comment by mesarpe** [comment]
Could you please try with an Ubuntu 16.04?
At the moment,I couldn't find the time to re create your environment.

My hypothesis is that your version of scipy is too old.

Alternative solution, create a virtual environment:

mkdir myenv
cd myenv
virtualenv .
pip install --upgrade pip
pip install scipy numpy (and the rest of dependencies)
git clone https://GitHub.com/mesarpe/sonetor
cd sonetor
python setup.py install

And give it a try there :)

**Comment by jhrbgergibbibfq** [comment]
Hi @mesarpe,

Thanks for your kind response. I've followed your last instructions, little bit progress move forward, I've done these steps:

- Installed Ubuntu 16.04
- Installed fresh Sonetor
- Run this command: ./sonetor.sh examples/example.ini /tmp/trace123
- Got bash: ./sonetor.sh: Permission denied error
- Run this command: sudo chmod +x sonetor.sh to give it permission
- Got this error: 

$ ./sonetor.sh examples/example.ini /tmp/trace123
Traceback (most recent call last):
  File "traffic.py", line 296, in <module>
    actions[u] = SelectSequences(config.get('MarkovChain', 'file'))
  File "traffic.py", line 222, in __init__
    self.g = networkx.read_gml(filename, relabel=True)
TypeError: read_gml() got an unexpected keyword argument 'relabel'

Now what should I do, please help me further.

Thanks

**Comment by mesarpe** [comment]
Hi,

The networkx API seem to have changed from version 1.9.1 onwards.

Please, execute the following command:

pip install networkx==1.9.1

Cheers
