### ISSUE TITLE
ConfigParser. 

### ISSUE THREAD

**Issue by hussain029** [mesarpe/sonetor#2]
**i write this command for generating regular traffic traces:** 
 ./sonetor.sh examples/example_positive.ini /tmp/trace1235
**Traceback (most recent call last):**
  File "traffic.py", line 47, in <module>
    COMMUNITIES_ENABLED = config.getboolean('General', 'communities_enabled')
  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 340, in get
    raise NoOptionError(option, section)
**ConfigParser.NoOptionError: No option 'communities_enabled' in section: 'General'**
Traceback (most recent call last):
  File "mobility.py", line 96, in <module>
    min_step = config.getfloat('Mobility', 'min_step') or 0.1
  File "/usr/lib/python2.7/ConfigParser.py", line 362, in getfloat
    return self._get(section, float, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
  File "/usr/lib/python2.7/ConfigParser.py", line 340, in get
    raise NoOptionError(option, section)
**ConfigParser.NoOptionError: No option 'min_step' in section: 'Mobility'**

**Comment by hussain029** [comment]
nothing
